:toc-title: Inhaltsverzeichnis
:toc:
:toclevels: 4

:tip-caption:  pass:[&#128681;]

:classdia-caption: Class diagram
:seqdia-caption: Sequence diagram

:source-highlighter: prettify

:imagesdir: ../../doc/images
:imagesoutdir: ../images
:testdir: ../../Tests
:sourcedir: ../../src
:plantumldir: ../plantuml
:rootdir: ../../
== Entwickler-Guide

=== Starte Cucumber-Scenario innerhalb der IDE (IntelliJ IDEA)

In den "run configuration":

* setze "main class" auf `io.cucumber.junit.TigerCucumberRunner`

* setze folgende "glue code packages"

[source]
----
net.serenitybdd.cucumber.actors
de.gematik.test.tiger.hooks
de.gematik.test.tiger.glue
de.gematik.tim.test.glue
----

Für die Entwicklung dieser Testsuite wurde das Tiger-Framework benutzt.
Im folgenden Link finden sie das link:https://gematik.github.io/app-Tiger/Tiger-User-Manual.html#_intellij[Tiger-Manual]
für weitere Informationen.

=== Disable TLS

Um TLS zu deaktivieren dürfen die Umgebungsvariablen nicht gesetzt werden und in der link:{rootdir}tiger.yml[tiger.yml] müssen Zeile 2 und 3. gelöscht werden

IMPORTANT: Zeile 1 "tigerProxy:" muss weiterhin stehen bleiben

[source,yml,linenums]
----
tigerProxy:
  tls:
    forwardMutualTlsIdentity: "${TIM_KEYSTORE};${TIM_KEYSTORE_PW};pkcs12"
----

Mit dieser Konfiguration müssen alle Links in der link:{sourcedir}/test/resources/combine_items.json[combine_items.json] auf `http` gesetzt werden.

=== Cucumber-Test-Combinations-Maven-Plugin

Das Parameter-Plugin erstellt aus den bereitgestellten Schnittstellen aus dem link:{sourcedir}/test/resources/combine_items.json[combine_items.json] alle nach den Filtern mögliche Kombinationen für jeden einzelnen Testfall. Hierzu werden alle Templates aus dem Testordner in den Buildordner kopiert und mit den jeweiligen Tabellen befüllt. Die so bearbeiteten Files werden beim starten der Testsuite herangezogen.

Bei einer geringen Anzahl von Schnittstellen mit zu wenig Variation in ihren Eigenschaften, kann es schnell dazu führen, dass das Plugin den Buildvorgang abbricht. Um dies zu ignorieren können die Schritte konfiguriert werden.

==== Disable prepare-items (autofill combine_items.json)

Per default fragt das Plugin die Info-Schnittstelle ab und fügt notwendige Tags und Properties hinzu.
Für eine genauere Steuerung oder sollte die Info-Schnittstelle noch nicht vollständig implementiert sein, kann die `combine_items.json` händisch erstellt und verwendet werden. Hierzu kann maven mit dem Profil `disable-prepare-items` verwendet werden.

----
maven clean install -P disable-prepare-items
----

==== Disable break

Mit dem Profil `dont-break-preperation` kann das Plugin so eingestellt werden, dass es bei Fehlern den Buildprozess nicht mehr abbricht. Alle möglichen Informationen und Kombinationen werden erstellt. Ein Fehlerlog kann später `./target/generated-combine/errorLog.txt` eingesehen werden.

=== Reuse claimed devices

Die Testsuite kann so eingestellt werden, dass sie Devices für die gesamte Laufzeit nicht unclaimed und bevorzugt die Devices verwendet, die bereits in Verwendung sind.

Hierzu kann in der Commandline `-DsaveConnections=true` gesetzt werden oder in der  pom.xml der Wert gesetzt werden.

Dieses Verhalten sorgt jedoch dafür, dass Devices gehalten werden und eine parallele Ausführung wird somit erschwert.

=== Claimzeit beeinflussen

Über den Parameter `-DclaimDuration=<seconds>` kann die Zeit beeinflusst werden, die ein Device geclaimed bleiben soll. Es sind nur ganzzahlige Sekundenwerte möglich.

=== Testcase id

Every testcase run is identified with the testcase name and an id that identifies the specific run. This id is sent in every request in the header `Test-Case-Id`. It is build like `<TestcaseId>/<TestrunUUID>`.

=== Known issues

. Es kann beim Generieren des Codes aus der link:https://github.com/gematik/api-ti-messenger/blob/main/src/openapi/TiMessengerTestTreiber.yaml[Testtreiberschnittstelle] passieren, dass zusätzliche `/` in den Requestpath erstellt werden. Diese können zu Inkompatibilitäten führen. Dies kann auf Seiten der Testsuite umgangen werden indem in der Klasse link:{sourcedir}/main/java/de/gematik/tim/test/glue/api/TestdriverApiPath.java[TestdriverApiPath] bei INFO_PATH und DEVICES_PATH der vorgestellte `/` entfernt wird.