:toc-title: Inhaltsverzeichnis
:toc:
:toclevels: 4

:tip-caption:  pass:[&#128681;]

:classdia-caption: Class diagram
:seqdia-caption: Sequence diagram

:source-highlighter: prettify

:imagesdir: ../../doc/images
:imagesoutdir: ../images
:testdir: ../../Tests
:sourcedir: ../../src
:plantumldir: ../plantuml
:rootdir: ../../
== Erste Schritte

=== Zertifikate einrichten

Die Testtreiberschnittstelle ist über mTls abgesichert. Da jegliche Kommunikation über den Tiger-Proxy läuft muss dem Tiger-Proxy ein Klient-Zertifikat mitgegeben werden. In diesem Kapitel wird beschrieben wie der Proxy richtig konfiguriert werden kenn.

==== Client-Zertifikat für mTLS einrichten

Die Testtreiberschnittstelle setzt auf mTLS.
Daher muss ein Client-Zertifikat bereitgestellt und dem Tiger Proxy übergeben werden. Die Testsuite ist so vorbereitet, dass Sie den Path und das Passwort unter folgenden Umgebungsvariablen erwartet:

* TIM_KEYSTORE
* TIM_KEYSTORE_PW

Sollte für Testzwecke ein selbstsigniertes Zertifikat verwendet werden muss zusätzlich noch ein Truststore konfiguriert werden. Dies geschieht über die Angabe der 2 Umgebungsvariablen:

* TIM_TRUSTSTORE
* TIM_TRUSTSTORE_PW

Die jeweiligen Stores sollten im .p12-Format sein.

Für lokale/interne Entwicklung kann das Verwenden von TLS umgangen werden.
Eine Anleitung hierzu ist link:DevGuide.adoc#Disable-TLS[hier] zu finden.

=== Testtreiberschnittstelle hinzufügen

Alle zu testenden Testtreiberschnittstellen werden in der Datei link:{sourcedir}/test/resources/combine_items.json[combine_items.json] verwaltet.
Um eine neue Testtreiberschnittstelle zur Testsuite hinzuzufügen, muss ein entsprechender Eintrag in dieser Datei ergänzt werden.

Der `value` in der link:{sourcedir}/test/resources/combine_items.json[combine_items.json] kann entweder direkt die vollständige URL oder für die bessere Zuordnung einen Alias darstellen.
Der Alias kann freie gewählt werden.
Sollte ein Alias verwendet werden muss die entsprechende URL unter `url` eingetragen werden.

.Ein Beispiel-Item mit Alias und URL
[source,json]
----
[
  {
      "value": "API1",
      "url": "https://<HOST_NAME>:<PORT>"
  },
  {
      "value": "API2",
      "url": "https://<HOST_NAME>:<PORT>/rest/"
  },
  {
      "value": "API3",
      "url": "https://<HOST_NAME>:<PORT>/ti-m-testtreiber"
  }
]
----

IMPORTANT: Für die Verwendung eines `alias` ist es ebenfalls nötig diesen in die link:{rootdir}tiger.yml[tiger.yml] nach folgendem Schema einzutragen!

[source,yml]
----
# default local Tiger Proxy
tigerProxy:
  tls:
    forwardMutualTlsIdentity: "${TIM_KEYSTORE};${TIM_KEYSTORE_PW};pkcs12" <1>
  proxyRoutes:
    - from: http://API1 <2>
      to: https://<HOST_NAME>:<PORT>
    - from: http://API2
      to: https://<HOST_NAME>:<PORT>/rest <3>
    - from: http://API3
      to: https://<HOST_NAME>:<PORT>/ti-m-testtreiber
----

<1> Default local Tiger muss bestehen bleiben.
<2> Unter `proxyRoutes` können die einzelnen Routen dem Proxy bekannt gemacht werden. From muss mit http:// beginnen und mit dem Value in link:{sourcedir}/test/resources/combine_items.json[combine_items.json] übereinstimmen.
<3> Weitere Ressourcen im Pfad müssen genannt werden

=== Starten der Testfälle

Die Testsuite führt die Tests als Maven-Integrationstests aus.
Gestartet wird die Testsuite mit diesem Befehl:

----
mvn verify
----

=== Auswerten der Testergebnisse

Nach der Testausführung liegt der aktuelle Report im Build-Verzeichnis unter link:{rootdir}target/site/serenity/index.html[target/site/serenity/index.html].
Wiederholte Ausführungen werden in einem gemeinsamen Report zusammengefasst.

Zusätzlich wird jeder Durchlauf mit seinem Report und den genutzten Feature-Dateien im Root-Verzeichnis im Ordner link:{rootdir}reports[reports] gespeichert.