:toc-title: Inhaltsverzeichnis
:toc:
:toclevels: 4

:tip-caption:  pass:[&#128681;]
:sectanchors:

:classdia-caption: Class diagram
:seqdia-caption: Sequence diagram

:source-highlighter: prettify

:imagesdir: ../../doc/images
:imagesoutdir: ../images
:testdir: ../../Tests
:sourcedir: ../../src
:plantumldir: ../plantuml
:rootdir: ../../
== Erste Schritte

=== Zertifikate einrichten

Die Testtreiberschnittstelle ist über mTls abgesichert.
Da jegliche Kommunikation über den Tiger-Proxy läuft muss dem Tiger-Proxy ein Client-Zertifikat mitgegeben werden.
Außerdem muss der Testtreiber mit den entsprechenden Zertifikaten versehen werden.
In diesem Kapitel wird beschrieben wie der Proxy richtig konfiguriert werden kann und eine unterstützende Anleitung gegeben, wie das Server-Zertifikat installiert wird.

Nach Beantragen einer Zulassung werden Sie aufgefordert Ihre URL's der von Ihnen bereitgestellten Schnittstellen zu liefern.
Für diese URL's erstellt die gematik ein Server-Zertifikat, ein Client-Zertifikat und alle dazugehörigen Keys.

==== Zertifikate extrahieren

Die Zertifikate bzw.
Keys können wie folgt aus dem `.p12`-File extrahiert werden (benötigte Passwörter stehen in der mitgelieferten `password`-Datei):

.Trusted-Zertifikat
[source,bash]
----
openssl pkcs12 -info --in gemTruststore.p12 -nokeys > trustedCert.pem
----

.Server-Zertifikat
[source,bash]
----
openssl pkcs12 -info --in <yourName>ServerKeystore.p12 -nokeys > serverCert.pem
----

.Server-Key
[source,bash]
----
openssl pkcs12 -info --in <yourName>ServerKeystore.p12 -nocerts > serverKey.pem
----

.Client-Zertifikat
[source,bash]
----
openssl pkcs12 -info --in <yourName>ClientKeystore.p12 -nokeys > clientCert.pem
----

.Client-Key
[source,bash]
----
openssl pkcs12 -info --in <yourName>ClientKeystore.p12 -nocerts > clientKey.pem
----

[IMPORTANT]
[red]#Wenn ein Key aus einer .p12 geladen wird, wird ein neues Passwort gesetzt.
Dieses muss nicht dem in der mitgelieferten `passwort`-Datei entsprechen.#

==== Server-Zertifikat einrichten

Eine genaue Anleitung ist hier nicht möglich.
Je nach verwendeter Technologie kann sich das Einrichten anders gestalten.
Das Zertifikat und die damit einhergehende Prüfung kann in der Anwendung direkt oder in einen vorgeschalteten Proxy geschehen.

[IMPORTANT]
[red]#*Die Schnittstelle muss TLSv1.2 unterstützen!*#

Beispielhaft ist hier eine Konfiguration mit einem nginx-proxy wie sie unter `_/etc/nginx/default.conf_` liegen könnte.
Gleichzeitig müssen die oben extrahierten

* Server-Key
* Server-Zertifikat
* Trusted-Zertifikate

unter `_etc/nginx/conf.d/certs/*_` abgelegt werden.
Außerdem muss eine `.txt`-Datei erstellt werden, die nur das ServerKey Passwort enthält (entweder das selbstgewählte, wenn das extrahierte Zertifikat aus dem Keystore genommen wird, oder das Passwort aus der passwort.txt Datei, wenn dieses nicht geändert wurde).

----
access_log   /dev/stdout;
error_log    /dev/stderr debug;

server {
    listen                     443 ssl default_server;

    ssl_protocols              TLSv1.2;

    ssl_certificate            conf.d/certs/serverCert.pem;
    ssl_certificate_key        conf.d/certs/serverKey.pem;
    ssl_password_file          conf.d/certs/pass-key.txt;

    ssl_verify_client          on;
    ssl_verify_depth           1;
    ssl_trusted_certificate    conf.d/certs/trustedCert.pem;

    charset                    utf-8;

    location / {
        ...
    }
}
----

==== Client-Zertifikat für mTLS einrichten

Die Testtreiberschnittstelle verwendet mTLS.
Daher muss ein Client-Zertifikat bereitgestellt und dem Tiger Proxy übergeben werden.
Die Testsuite ist so vorbereitet, dass Sie den Path und das Passwort unter folgenden Umgebungsvariablen erwartet:

* TIM_KEYSTORE
* TIM_KEYSTORE_PW

Sollte für Testzwecke ein selbstsigniertes Zertifikat verwendet werden muss zusätzlich noch ein Truststore konfiguriert werden.
Dies geschieht über die Angabe der 2 Umgebungsvariablen:

* TIM_TRUSTSTORE
* TIM_TRUSTSTORE_PW

Die jeweiligen Stores sollten im .p12-Format sein.

Für lokale/interne Entwicklung kann das Verwenden von TLS umgangen werden.
Eine Anleitung hierzu ist link:DevGuide.adoc#Disable-TLS[hier] zu finden.

=== Testtreiberschnittstelle hinzufügen

Alle zu testenden Testtreiberschnittstellen werden in der Datei link:{sourcedir}/test/resources/combine_items.json[combine_items.json] verwaltet.
Um eine neue Testtreiberschnittstelle zur Testsuite hinzuzufügen, muss ein entsprechender Eintrag in dieser Datei ergänzt werden.

Der `value` in der link:{sourcedir}/test/resources/combine_items.json[combine_items.json] kann entweder direkt die vollständige URL oder für die bessere Zuordnung einen Alias darstellen.
Der Alias kann freie gewählt werden.
Sollte ein Alias verwendet werden muss die entsprechende URL unter `url` eingetragen werden.

.Ein Beispiel-Item mit Alias und URL
[source,json]
----
[
  {
      "value": "API1",
      "url": "https://<HOST_NAME>:<PORT>"
  },
  {
      "value": "API2",
      "url": "https://<HOST_NAME>:<PORT>/rest/"
  },
  {
      "value": "API3",
      "url": "https://<HOST_NAME>:<PORT>/ti-m-testtreiber"
  }
]
----

IMPORTANT: Für die Verwendung eines `alias` ist es ebenfalls nötig diesen in die link:{rootdir}tiger.yml[tiger.yml] nach folgendem Schema einzutragen!

[source,yml]
----
# default local Tiger Proxy
tigerProxy:
  tls:
    forwardMutualTlsIdentity: "${TIM_KEYSTORE};${TIM_KEYSTORE_PW};pkcs12" <1>
  proxyRoutes:
    - from: http://API1 <2>
      to: https://<HOST_NAME>:<PORT>
    - from: http://API2
      to: https://<HOST_NAME>:<PORT>/rest <3>
    - from: http://API3
      to: https://<HOST_NAME>:<PORT>/ti-m-testtreiber
----

<1> Default local Tiger muss bestehen bleiben.
<2> Unter `proxyRoutes` können die einzelnen Routen dem Proxy bekannt gemacht werden.
From muss mit http:// beginnen und mit dem Value in link:{sourcedir}/test/resources/combine_items.json[combine_items.json] übereinstimmen.
<3> Weitere Ressourcen im Pfad müssen genannt werden

=== Starten der Testfälle

Die Testsuite führt die Tests als Maven-Integrationstests aus.
Gestartet wird die Testsuite mit diesem Befehl:

----
mvn verify
----

[[parameter_controll_testsuite,Parameter für die Steuerung der Testsuite]]
==== Parameter die das Verhalten der Testsuite anpassen

Um für einige Gegebenheiten vorbereitet zu sein, kann die Testsuite ihr Verhalten leicht anpassen.
Im Folgenden sind Parameter aufgezählt die alle mittels -D<parameterName>(=<parameterValue>) mit beim Aufruf angegeben werden können

.Parameter zum Anpassen der Testsuite
[%header,cols='2,4,1']
|===
|Parametername|Wirkung|defaultValue
|maxRetryClaimRequest|Legt fest wie häufig ein Claimen eines Devices fehlschlagen darf bevor es zum Abbruch kommt|3
|timeout|Legt fest wie lange auf nach eine Request erneut gesendet wird bis die erwartete Antwort erscheint|10 Sek
|pollInterval|Legt fest, in welchen Abständen eine erneute Anfrage gesendet wird bis die erwartete Antwort erscheint|1 Sek
|httpTimeout|Legt fest wie lange die Testsuite auf eine Antwort der Testtreiberschnittstelle wartet|180 Sek
|claimDuration|Ist der Wert der bei einer Claim-Request mitgesendet wird|180
|runWithoutRetry|Sendet eine Anfrage nur einmal aus und geht davon aus, dass es keine Synchronisationsprobleme gibt|false
|clearRooms|Jeder User fragt am Anfang seine Räume ab und verlässt alle. Dies bedeutet Einbußen in der Performance und ist nur zum Säubern des Setups gedacht|false
|skipRoomStateCheck|Das failen der Prüfung ob jeder Room Member den richtigen MemberShipState hat, lässt die Testsuite nicht fehlschlagen, sondern führt nur zu einem individuellem Logeintrag wenn Wert auf `true`  gesetzt wird|false
|===

=== Auswerten der Testergebnisse

Nach der Testausführung liegt der aktuelle Report im Build-Verzeichnis unter link:{rootdir}target/site/serenity/index.html[target/site/serenity/index.html].
Wiederholte Ausführungen werden in einem gemeinsamen Report zusammengefasst.

Zusätzlich wird jeder Durchlauf mit seinem Report und den genutzten Feature-Dateien im Root-Verzeichnis im Ordner link:{rootdir}reports[reports] gespeichert.